services:
  app:
    build:
      context: .
      target: production
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/nauht
  db:
   image: postgres
   restart: always
   volumes:
     - db-data:/var/lib/postgresql/data
   environment:
     - POSTGRES_DB=nauth
     - POSTGRES_USER=nauth
     - POSTGRES_PASSWORD=nauth
   expose:
     - 5432
   healthcheck:
     test: [ "CMD", "pg_isready", "-U", "nauth" ]
     interval: 10s
     timeout: 5s
     retries: 5
volumes:
 db-data:
